### ISSUE TITLE
Uncaught exception on failing hook

### ISSUE THREAD

**Issue by langri-sha** [mochajs/mocha#2146]
I am using the latest __2.4.5__ release and the HTML reporter. When a hook fails, an uncaught exception is thrown and the runner simply stops.

```
describe "test", ->
  beforeEach "bar is not defined", ->
    foo = bar

  it "fails without feedback", ->
```

```
Uncaught TypeError: Cannot read property 'replace' of undefinedBuffer.39.exports.clean @ mocha.js:5937(anonymous function) @ mocha.js:2518Buffer.3.EventEmitter.emit @ mocha.js:200(anonymous function) @ mocha.js:2451Buffer.3.EventEmitter.emit @ mocha.js:200Buffer.36.Runner.fail @ mocha.js:4564Buffer.36.Runner.failHook @ mocha.js:4593(anonymous function) @ mocha.js:4638done @ mocha.js:4251Buffer.35.Runnable.run @ mocha.js:4267next @ mocha.js:4629(anonymous function) @ mocha.js:4651timeslice @ mocha.js:12619
```

![image](https://cloud.githubusercontent.com/assets/77084/13568204/f863864c-e45f-11e5-95f0-db2478b791b9.png)

Works fine in Node otherwise.

**Comment by lss876** [comment]
same here. have you solved it? @langri-sha

**Comment by MiguelCastillo** [comment]
This makes refactoring my code really painful. :/

**Comment by MiguelCastillo** [comment]
Actually, this is already fixed.

https://github.com/mochajs/mocha/pull/2086

:D

**Comment by lss876** [comment]
Hi @MiguelCastillo , it doesn't work here.  i use commit [9ae6a85]. 

![2016-03-14_095156](https://cloud.githubusercontent.com/assets/3126264/13733176/8113fe44-e9ca-11e5-936c-906302537c96.jpg)

**Comment by danielstjules** [comment]
Should be fixed in master. You need to first run `make` so that you're using an updated version of mocha.js :)

**Comment by langri-sha** [comment]
@danielstjules cloned tip, clean `npm install`, ran `make clean all` and I am still getting the same error with the HTML reporter.

**Comment by josephmcasey** [comment]
I am using mocha 2.5.3. I am still seeing this exact same failure testing via browser, Chrome Version 51.0.2704.84 (64-bit).

**Comment by ScottFreeCode** [comment]
@josephmcase Can you give us a minimal set of code that reproduces this issue? The screenshot isn't telling us much besides the fact that it happened.
