### ISSUE TITLE
Suite `only` not anchored to title start

### ISSUE THREAD

**Issue by ScottFreeCode** [mochajs/mocha#2298]
In the process of looking into https://github.com/mochajs/mocha/issues/2157#issuecomment-224475198, I noticed that the BDD interface's `it.only` escapes the regular expression and requires it to match the whole title with `^` and `$`, but `describe.only` merely passes the string to `grep`, which escapes it but does not require it to begin with `^`. This same issue also affects the QUnit and TDD interfaces.

Contrived example:
```js
describe.only("one", function() {
  it("two", function() { /* succeed */ })
})
describe("you know", function() {
  it("one of these should not run", function() {
    throw new Error("Specifically, this one should not run!")
  })
})
```

**Comment by ScottFreeCode** [comment]
Something similar goes for the links in the HTML reporter; the test ones should use `^` and `$` to require matching the whole title, and the suite ones should use `^` to require matching the start of the title.

**Comment by boneskull** [comment]
@ScottFreeCode I merged bbeeff09c2dff0790b7358d4cf37b57661c04ce9 into v3.0.0 branch.  does this solve the issue?

**Comment by ScottFreeCode** [comment]
Sorry I missed this!

Making `only` programmatic resolved the primary issue here.

It looks like the HTML links still have the same sort of problem, however. Do we have another issue for it? If not, I will open one instead of keeping this issue open for it.
